# Generated by Django 3.0.6 on 2020-06-14 17:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_auto_20200614_2325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='To',
        ),
    ]
