# Generated by Django 3.0.6 on 2020-06-14 18:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0003_auto_20200614_2329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='To',
            new_name='Todo',
        ),
    ]
